# Generated by Django 4.2.7 on 2026-01-28 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code_used', models.CharField(max_length=20)),
                ('tier_level', models.IntegerField(default=1, help_text='1=direct, 2=indirect, 3=3rd level')),
                ('status', models.CharField(choices=[('pending', 'Pending - Awaiting deposit'), ('active', 'Active - Bonus earned'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('first_deposit_made', models.BooleanField(default=False)),
                ('first_deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('first_deposit_date', models.DateTimeField(blank=True, null=True)),
                ('referee_bonus_given', models.BooleanField(default=False)),
                ('referrer_bonus_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('parent_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_referrals', to='referrals.referral')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_user', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'db_table': 'referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Program', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('referee_bonus_amount', models.DecimalField(decimal_places=2, default=500.0, help_text='Bonus for new user who signs up', max_digits=10)),
                ('referrer_bonus_amount', models.DecimalField(decimal_places=2, default=1000.0, help_text='Bonus for existing user who referred', max_digits=10)),
                ('referrer_bonus_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='Percentage of referee first deposit', max_digits=5)),
                ('enable_multi_tier', models.BooleanField(default=True)),
                ('tier2_bonus_percent', models.DecimalField(decimal_places=2, default=2.0, help_text='% bonus for tier 2 referrals', max_digits=5)),
                ('tier3_bonus_percent', models.DecimalField(decimal_places=2, default=1.0, help_text='% bonus for tier 3 referrals', max_digits=5)),
                ('minimum_deposit_required', models.DecimalField(decimal_places=2, default=5000.0, help_text='Min deposit for referee to activate bonus', max_digits=10)),
                ('bonus_expiry_days', models.IntegerField(default=90, help_text='Days before bonus expires')),
                ('max_referrals_per_user', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('max_bonus_per_referral', models.DecimalField(decimal_places=2, default=0, help_text='0 = unlimited', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Program',
                'verbose_name_plural': 'Referral Programs',
                'db_table': 'referrals_program',
            },
        ),
        migrations.CreateModel(
            name='ReferralLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('all_time', 'All Time')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_referrals', models.IntegerField(default=0)),
                ('active_referrals', models.IntegerField(default=0)),
                ('total_bonus_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tier1_referrals', models.IntegerField(default=0)),
                ('tier2_referrals', models.IntegerField(default=0)),
                ('tier3_referrals', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0, help_text='Points for gamification')),
                ('prize_awarded', models.BooleanField(default=False)),
                ('prize_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Leaderboard',
                'verbose_name_plural': 'Referral Leaderboards',
                'db_table': 'referral_leaderboard',
                'ordering': ['period_type', '-points', '-total_referrals'],
                'indexes': [models.Index(fields=['period_type', '-rank'], name='referral_le_period__7a04f9_idx'), models.Index(fields=['user', 'period_type'], name='referral_le_user_id_ff7457_idx')],
                'unique_together': {('user', 'period_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('signup', 'Sign-up Bonus'), ('deposit', 'Deposit Bonus'), ('tier1', 'Tier 1 Bonus'), ('tier2', 'Tier 2 Bonus'), ('tier3', 'Tier 3 Bonus'), ('special', 'Special Bonus')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('distributed', 'Distributed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='referrals.referral')),
            ],
            options={
                'verbose_name': 'Referral Bonus',
                'verbose_name_plural': 'Referral Bonuses',
                'db_table': 'referral_bonuses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='referral_bo_recipie_4759f2_idx'), models.Index(fields=['status'], name='referral_bo_status_c7b250_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('new_referrals', models.IntegerField(default=0)),
                ('activated_referrals', models.IntegerField(default=0)),
                ('bonuses_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonuses_distributed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_referrals', models.IntegerField(default=0)),
                ('total_active_referrals', models.IntegerField(default=0)),
                ('total_bonuses_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_bonuses_pending', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Analytics',
                'verbose_name_plural': 'Referral Analytics',
                'db_table': 'referral_analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='referral_an_user_id_57e031_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', '-created_at'], name='referrals_referre_e90716_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referee'], name='referrals_referee_e3d989_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status'], name='referrals_status_135a0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referrer', 'referee')},
        ),
    ]
