# Generated by Django 4.2.7 on 2026-01-26 01:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable/disable bot trading')),
                ('strategy', models.CharField(choices=[('conservative', 'Conservative - Low Risk'), ('balanced', 'Balanced - Medium Risk'), ('aggressive', 'Aggressive - High Risk')], default='balanced', max_length=20)),
                ('daily_trading_limit', models.DecimalField(decimal_places=2, default=Decimal('1000'), help_text='Maximum amount to trade per day', max_digits=12)),
                ('max_trades_per_day', models.IntegerField(default=5, help_text='Maximum number of trades per day')),
                ('take_profit_percentage', models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Take profit at X% gain', max_digits=5)),
                ('stop_loss_percentage', models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='Stop loss at X% loss', max_digits=5)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bot_config',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BotTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('asset', models.CharField(default='USD', help_text='Asset being traded', max_length=20)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('was_auto_executed', models.BooleanField(default=True, help_text='Was this trade auto-executed by bot')),
                ('triggered_by', models.CharField(default='scheduled', help_text='What triggered this trade: scheduled, price_action, signal, manual', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Trade notes or analysis')),
                ('bot_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='bot.botconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bot_trade',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='BotExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('started', 'Bot Started'), ('stopped', 'Bot Stopped'), ('trade_executed', 'Trade Executed'), ('trade_closed', 'Trade Closed'), ('error', 'Error'), ('config_updated', 'Config Updated')], max_length=20)),
                ('event_message', models.TextField()),
                ('event_data', models.JSONField(default=dict, help_text='Additional event data as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='bot.botconfig')),
                ('related_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.bottrade')),
            ],
            options={
                'db_table': 'bot_execution_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('trades_count', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('average_trade_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('largest_win', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('largest_loss', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('ending_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='bot.botconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bot_performance',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['bot_config', 'period_type', 'period_end'], name='bot_perform_bot_con_3be2a8_idx'), models.Index(fields=['user', 'period_type'], name='bot_perform_user_id_405bb0_idx')],
            },
        ),
    ]
