# Generated by Django 4.2.7 on 2026-01-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_devicetracking_failedloginattempt_securitylog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_deposit', models.BooleanField(default=True)),
                ('email_withdrawal', models.BooleanField(default=True)),
                ('email_profit', models.BooleanField(default=True)),
                ('email_referral', models.BooleanField(default=True)),
                ('email_security', models.BooleanField(default=True)),
                ('email_kyc', models.BooleanField(default=True)),
                ('email_system', models.BooleanField(default=True)),
                ('sms_deposit', models.BooleanField(default=False)),
                ('sms_withdrawal', models.BooleanField(default=True)),
                ('sms_security', models.BooleanField(default=True)),
                ('inapp_all', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='users.user')),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit_confirmation', 'Deposit Confirmation'), ('withdrawal_confirmation', 'Withdrawal Confirmation'), ('profit_update', 'Profit Update'), ('referral_bonus', 'Referral Bonus'), ('security_alert', 'Security Alert'), ('kyc_update', 'KYC Update'), ('system_announcement', 'System Announcement'), ('general', 'General')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['type', '-created_at'], name='notificatio_type_d2e2f1_idx')],
            },
        ),
    ]
