# Generated by ChatGPT on 2026-01-21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
