# Generated by Django 4.2.7 on 2026-01-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.user')),
            ],
            options={
                'db_table': 'device_tracking',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_or_user_id', models.CharField(max_length=255)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('reason', models.CharField(choices=[('invalid_credentials', 'Invalid Credentials'), ('account_suspended', 'Account Suspended'), ('account_inactive', 'Account Inactive'), ('invalid_2fa', 'Invalid 2FA Code'), ('user_not_found', 'User Not Found')], max_length=100)),
            ],
            options={
                'db_table': 'failed_login_attempts',
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['-attempt_time'], name='failed_logi_attempt_445b11_idx'), models.Index(fields=['ip_address', '-attempt_time'], name='failed_logi_ip_addr_77a9c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('password_changed', 'Password Changed'), ('email_changed', 'Email Changed'), ('phone_changed', 'Phone Changed'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('unusual_login', 'Unusual Login Activity'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('suspicious_activity', 'Suspicious Activity Detected'), ('new_device', 'New Device Detected'), ('device_removed', 'Device Removed'), ('multiple_failed_logins', 'Multiple Failed Logins')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to='users.devicetracking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='users.user')),
            ],
            options={
                'db_table': 'security_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='security_lo_user_id_7828de_idx'), models.Index(fields=['event_type', '-created_at'], name='security_lo_event_t_e67194_idx'), models.Index(fields=['severity', '-created_at'], name='security_lo_severit_256943_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('success', models.BooleanField(default=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='users.user')),
            ],
            options={
                'db_table': 'login_history',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='login_histo_user_id_c59338_idx'), models.Index(fields=['-login_time'], name='login_histo_login_t_365f72_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='devicetracking',
            index=models.Index(fields=['user', '-last_seen'], name='device_trac_user_id_ac0750_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetracking',
            index=models.Index(fields=['device_id'], name='device_trac_device__308431_idx'),
        ),
    ]
