# Generated by Django 4.2.7 on 2026-01-26 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin - Full Access'), ('admin', 'Admin - Platform Management'), ('moderator', 'Moderator - User Support'), ('analyst', 'Analyst - Reporting Only')], default='moderator', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('can_suspend_users', models.BooleanField(default=False)),
                ('can_adjust_transactions', models.BooleanField(default=False)),
                ('can_verify_kyc', models.BooleanField(default=False)),
                ('can_manage_admins', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'admin_adminuser',
            },
        ),
        migrations.CreateModel(
            name='PlatformStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('suspended_users', models.IntegerField(default=0)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_profit_generated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_fees_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('assets_under_management', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_transactions', models.IntegerField(default=0)),
                ('new_deposits', models.IntegerField(default=0)),
                ('new_withdrawals', models.IntegerField(default=0)),
                ('kyc_verified', models.IntegerField(default=0)),
                ('kyc_pending', models.IntegerField(default=0)),
                ('kyc_rejected', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Statistics',
                'verbose_name_plural': 'Platform Statistics',
                'db_table': 'admin_platformstatistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Quantum Capital', max_length=100)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('maximum_withdrawal', models.DecimalField(decimal_places=2, default=500000, max_digits=10)),
                ('deposits_enabled', models.BooleanField(default=True)),
                ('withdrawals_enabled', models.BooleanField(default=True)),
                ('referrals_enabled', models.BooleanField(default=True)),
                ('kyc_required_for_withdrawal', models.BooleanField(default=True)),
                ('bot_trading_enabled', models.BooleanField(default=True)),
                ('mpesa_enabled', models.BooleanField(default=False)),
                ('crypto_enabled', models.BooleanField(default=False)),
                ('email_notifications_enabled', models.BooleanField(default=False)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('kyc_verification_level', models.IntegerField(default=1)),
                ('kyc_auto_approve_documents', models.BooleanField(default=False)),
                ('kyc_expiry_months', models.IntegerField(default=12)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('login_lockout_minutes', models.IntegerField(default=30)),
                ('force_2fa', models.BooleanField(default=False)),
                ('sentry_enabled', models.BooleanField(default=False)),
                ('health_check_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.adminuser')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
                'db_table': 'admin_systemconfiguration',
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('suspend_user', 'Suspend User'), ('activate_user', 'Activate User'), ('create_user', 'Create User'), ('adjust_transaction', 'Adjust Transaction'), ('verify_kyc', 'Verify KYC'), ('reject_kyc', 'Reject KYC'), ('approve_withdrawal', 'Approve Withdrawal'), ('reject_withdrawal', 'Reject Withdrawal'), ('adjust_balance', 'Adjust Balance'), ('create_admin', 'Create Admin User'), ('delete_admin', 'Delete Admin User'), ('change_permission', 'Change Permission'), ('export_report', 'Export Report'), ('system_config', 'System Configuration')], max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='admin_panel.adminuser')),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Log',
                'verbose_name_plural': 'Admin Logs',
                'db_table': 'admin_adminlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='admin_admin_admin_i_63f5e8_idx'), models.Index(fields=['affected_user', '-created_at'], name='admin_admin_affecte_bdecc6_idx'), models.Index(fields=['action_type', '-created_at'], name='admin_admin_action__0a62fd_idx')],
            },
        ),
    ]
