# Generated by Django 4.2.7 on 2026-01-26 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License")], max_length=20)),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('document_front_url', models.URLField(blank=True, null=True)),
                ('document_back_url', models.URLField(blank=True, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('address_proof_url', models.URLField(blank=True, null=True)),
                ('selfie_url', models.URLField(blank=True, null=True)),
                ('selfie_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('verification_level', models.IntegerField(default=1)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_document', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verified', to='admin_panel.adminuser')),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'db_table': 'kyc_kydocument',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCRejectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('document_quality', 'Document Quality'), ('information_mismatch', 'Information Mismatch'), ('expired_document', 'Expired Document'), ('suspicious_activity', 'Suspicious Activity'), ('other', 'Other')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'KYC Rejection Template',
                'verbose_name_plural': 'KYC Rejection Templates',
                'db_table': 'kyc_rejectiontemplate',
            },
        ),
        migrations.CreateModel(
            name='KYCWithdrawalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_level', models.IntegerField(choices=[(1, 'Level 1 - Basic'), (2, 'Level 2 - Enhanced'), (3, 'Level 3 - Full')], unique=True)),
                ('daily_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'KYC Withdrawal Limit',
                'verbose_name_plural': 'KYC Withdrawal Limits',
                'db_table': 'kyc_withdrawallimit',
            },
        ),
        migrations.CreateModel(
            name='KYCVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Document Submitted'), ('auto_approved', 'Auto Approved'), ('manual_approved', 'Manually Approved'), ('requested_resubmit', 'Requested Resubmission'), ('rejected', 'Rejected'), ('expired', 'Marked as Expired')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('verification_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='kyc.kycdocument')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_actions', to='admin_panel.adminuser')),
            ],
            options={
                'verbose_name': 'KYC Verification Log',
                'verbose_name_plural': 'KYC Verification Logs',
                'db_table': 'kyc_kycverificationlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
