# Generated by Django 4.2.7 on 2026-01-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_devicetracking_failedloginattempt_securitylog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('improvement', 'Improvement'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('attachment', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('under_consideration', 'Under Consideration'), ('accepted', 'Accepted/Planned'), ('implemented', 'Implemented'), ('rejected', 'Rejected')], default='pending_review', max_length=25)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to='users.user')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='users.user')),
            ],
            options={
                'db_table': 'suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='suggestions.suggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_votes', to='users.user')),
            ],
            options={
                'db_table': 'suggestion_votes',
                'indexes': [models.Index(fields=['suggestion', 'vote_type'], name='suggestion__suggest_3bb76f_idx')],
                'unique_together': {('suggestion', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['status', '-created_at'], name='suggestions_status_e562e9_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['category', '-created_at'], name='suggestions_categor_5c2779_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['-upvotes'], name='suggestions_upvotes_fdb255_idx'),
        ),
    ]
